#include "cli.hpp"

void print_help() {
    std::println(
        "CELERIS — GPU-ready metalens design via rigorous coupled-wave analysis\n"
        "\n"
        "Usage:\n"
        "  celeris design [options]   design a metalens -> GDSII + report\n"
        "  celeris widefov [options]  wide-FOV design: hyperbolic vs quadratic-phase\n"
        "                             lens, off-axis Strehl sweep (the FOV trade)\n"
        "  celeris efficiency [opts]  meta-atom energy budget: R / T / absorption +\n"
        "                             per-diffraction-order split (stray-light budget)\n"
        "  celeris fieldmap [options] full-field PSF/Strehl grid over a 2D field-angle\n"
        "                             sweep (the off-axis quality map, not just a row)\n"
        "  celeris validate [options] credibility battery on real TiO2 n,k:\n"
        "                             convergence + meta-atom + end-to-end report\n"
        "  celeris reproduce [opts]   reproduce a published metalens (Khorasaninejad\n"
        "                             Science 2016): conversion eff vs paper + focusing\n"
        "  celeris materials [opts]   list the built-in material library (real n,k)\n"
        "  celeris selftest           run the physics validation suite\n"
        "  celeris help               show this message\n"
        "\n"
        "design options (defaults):\n"
        "  --focal <µm=50>        focal length\n"
        "  --diameter <µm=20>     lens aperture diameter\n"
        "  --wavelength <µm=0.532>\n"
        "  --period <µm=0.35>     unit-cell pitch\n"
        "  --thickness <µm=0.6>   pillar height\n"
        "  --profile <focusing|quadratic|vortex|deflector|axicon|freeform=focusing>\n"
        "    (quadratic = parabolic wide-FOV lens; see `celeris widefov`)\n"
        "    --charge l / --deflect-deg / --deflect-azimuth / --axicon-deg   profile params\n"
        "    --freeform-file <grid.txt> --freeform-extent <µm>  loaded phi(x,y) hologram\n"
        "    --recon-z <µm=focal>   plane to reconstruct a non-focusing profile at\n"
        "  --auto-height          sweep height for full-2π coverage, ignore --thickness\n"
        "    --height-lo/-hi/-steps <0.30/1.20/12>  the height sweep range\n"
        "  --shape <square|circle|cross|ring=square>  meta-atom cross-section\n"
        "    --shape-param <0.5>  cross arm width / ring inner-radius (fraction)\n"
        "  --pillar <name>        pillar material by registry name (tio2|gan|a-si|\n"
        "                         c-si|si3n4|au|ag|al|... -- see `celeris materials`)\n"
        "  --pillar-n <2.4>       OR a constant pillar index (lossless)\n"
        "  --pillar-csv <file>    OR load pillar n,k from a CSV (highest precedence)\n"
        "  --substrate <name=bk7> substrate by registry name (bk7|sio2|air|sapphire|...)\n"
        "  --fill-samples <18>    library resolution\n"
        "  --harmonics <6>        RCWA Fourier half-count (accuracy vs speed)\n"
        "  --out <metalens.gds>   output GDSII path\n"
        "  --tolerance            Monte-Carlo fabrication-error / yield analysis\n"
        "  --fov                  off-axis field-of-view analysis\n"
        "  --psf <file.pgm>       write the focal-spot image (PGM)\n"
        "  --report <prefix>      write a full deliverable bundle (txt metrics +\n"
        "                         PSF & caustic images + GDS)\n"
        "\n"
        "celeris widefov [--focal 30] [--diameter 16] [--max-angle 30] [--angle-step 3]\n"
        "                [--auto-height] [--wavelength --period --thickness --pillar-n\n"
        "                --substrate --fill-samples --harmonics]\n"
        "  design a hyperbolic AND a quadratic-phase lens for the same f/D from the\n"
        "  same library, sweep the incidence (field) angle, and report each lens's\n"
        "  relative Strehl vs angle + the FOV half-angle: the quadratic lens holds a\n"
        "  sharp focus over a much wider field (its spot just shifts to ~f*sin(θ))\n"
        "  while the hyperbolic lens develops coma -- the classic wide-FOV trade.\n"
        "\n"
        "celeris efficiency [--fill 0.5] [--wavelength 0.532] [--period 0.35]\n"
        "                   [--thickness 0.6] [--pillar <name>|--pillar-n 2.4]\n"
        "                   [--substrate bk7] [--shape square|circle|cross|ring]\n"
        "                   [--pol x|y] [--harmonics 8]\n"
        "  one meta-atom's energy budget: reflection, transmission, absorption\n"
        "  (1-R-T, real for lossy metals), and the per-diffraction-order split --\n"
        "  how much lands in the useful 0th order vs higher (stray) orders. A\n"
        "  subwavelength pitch (Λ<λ) has only the 0th order propagating by design.\n"
        "\n"
        "celeris fieldmap [--focal 50] [--diameter 20] [--max-angle 12]\n"
        "                 [--angle-steps 4] [--psf-n 101] [--wavelength --period\n"
        "                 --thickness --pillar|--pillar-n --substrate --fill-samples\n"
        "                 --harmonics] [--out <map.pgm>]\n"
        "  full-field Strehl/FWHM map: designs a focusing lens, sweeps a 2D grid of\n"
        "  field angles (θx,θy) to ±max-angle (2*angle-steps+1 per axis), and prints\n"
        "  the relative-Strehl grid + diagonal FWHM trend + the FOV half-angle. The\n"
        "  full-field generalization of `design --fov` (which is just the center row).\n"
        "\n"
        "celeris birefringence [--fill-y 0.5] [--period --wavelength --thickness\n"
        "                       --pillar-n --samples --harmonics]\n"
        "  sweep a rectangular pillar's x-width; report x/y-polarized phase and\n"
        "  retardance (the polarization-optics / waveplate building block)\n"
        "\n"
        "celeris polardesign [--focal-x 50] [--focal-y 80] [--diameter --wavelength\n"
        "                    --period --thickness --pillar-n --samples --out\n"
        "                    --report <prefix>]\n"
        "  polarization-multiplexed lens: X-pol and Y-pol focus at different\n"
        "  distances; writes a rectangular-pillar GDS (+ report bundle)\n"
        "\n"
        "celeris pbdesign [--profile focusing|vortex|deflector|axicon|freeform] [--focal 50]\n"
        "                 [--charge 1] [--deflect-deg 10] [--deflect-azimuth 0]\n"
        "                 [--axicon-deg 5] [--freeform-file <grid.txt> --freeform-extent <µm>]\n"
        "                 [--recon-z <µm>] [--diameter --wavelength --period\n"
        "                 --thickness --pillar-n --samples --harmonics\n"
        "                 --handedness 1 --out --report <prefix>]\n"
        "  Pancharatnam-Berry (geometric-phase) metasurface: one half-wave-plate\n"
        "  atom rotated per site imprints 2*theta = any phi(x,y) on circularly\n"
        "  polarized light. Profiles: focusing lens, vortex/OAM plate (--charge l),\n"
        "  beam deflector (--deflect-deg), axicon/Bessel (--axicon-deg), or a freeform\n"
        "  hologram loaded from a phase-grid file. RCWA-verifies the 2*theta\n"
        "  relation, writes a rotated-pillar GDS");
    std::println(
        "celeris achromatic [--focal 30] [--diameter 10] [--wavelength 0.532]\n"
        "                 [--bandwidth 0.20] [--band-samples 7] [--period 0.35]\n"
        "                 [--height-lo 0.4 --height-hi 1.4 --height-steps 10]\n"
        "                 [--single-etch [--height 1.10]]\n"
        "                 [--pillar-n 2.4 | --pillar-csv <f>] [--fill-samples 24]\n"
        "                 [--harmonics 6] [--gd-weight 1.0]\n"
        "                 [--substrate sio2|bk7|air] [--out --report <prefix>]\n"
        "  Broadband (achromatic) focusing metalens by dispersion engineering:\n"
        "  characterizes a fill x height meta-atom library across the band (phase +\n"
        "  group delay per atom), then picks per site the atom matching BOTH the\n"
        "  base phase and the radius-dependent group delay. Reports the group-delay\n"
        "  budget and the chromatic focal drift vs a dispersion-blind baseline.\n"
        "  --single-etch spans (phase, group delay) with SHAPE variety at ONE height\n"
        "  (square/circle/cross/ring) -> fabricable in a single etch, no grayscale");
    std::println(
        "celeris pbachromatic [--focal 30] [--diameter 10] [--wavelength 0.532]\n"
        "                 [--bandwidth 0.20] [--band-samples 7] [--period 0.35]\n"
        "                 [--height 1.10] [--handedness 1] [--fill-samples 12]\n"
        "                 [--pillar-n 2.4 | --pillar-csv <f>] [--harmonics 6]\n"
        "                 [--gd-weight 1.0] [--substrate bk7|sio2|air] [--out --report <prefix>]\n"
        "  Achromatic Pancharatnam-Berry metalens -- the modern recipe: geometric\n"
        "  (PB) phase sets the base profile EXACTLY (rotation) while a dispersive\n"
        "  birefringent atom (chosen per radius from a fill_x x fill_y grid at ONE\n"
        "  etch depth) supplies the group delay. Base-phase RMS ~0 by construction;\n"
        "  the achromatic limit is only the library's group-delay coverage. Writes a\n"
        "  rotated-rectangle GDS (single mask layer)");
    std::println(
        "celeris reproduce [--device k2016-405|k2016-532|k2016-660|all|chen2018=k2016-532]\n"
        "                 [--diameter 20] [--harmonics 8]\n"
        "                 [--pillar-csv data/TiO2_Siefke.csv] [--report <prefix>]\n"
        "  Reproduce the canonical visible metalens (Khorasaninejad et al., Science\n"
        "  352, 1190 (2016)): NA=0.80 PB-phase TiO2 nanofins, H=600 nm, designed at\n"
        "  405/532/660 nm (reported focusing efficiency 86/73/66%). Solves the\n"
        "  PUBLISHED nanofin geometry with the real Siefke-2016 ALD-TiO2 n,k, reports\n"
        "  the RCWA conversion efficiency (upper bound on the paper's number),\n"
        "  RCWA-verifies the 2*theta geometric phase, and shows a diffraction-limited\n"
        "  focal spot. --device all runs all three. --report writes txt + rotated GDS.\n"
        "  --device chen2018 reproduces the BROADBAND ACHROMATIC device (Chen et al.,\n"
        "  Nat. Nanotechnol. 13, 220 (2018)): NA=0.20 TiO2 achromat, D=26.4 um, H=600\n"
        "  nm, 470-670 nm -- shows the required group-delay span sits at the 600-nm-\n"
        "  nanofin ceiling (the diameter is GD-limited) and the achromatic objective\n"
        "  flattens the chromatic focal drift (geometric phase + dispersion, one etch)");
}
